// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NinjAPI.Data;

#nullable disable

namespace NinjAPI.Migrations
{
    [DbContext(typeof(GymContext))]
    [Migration("20240118123904_ManyToOnev2")]
    partial class ManyToOnev2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NinjAPI.Models.Ninja", b =>
                {
                    b.Property<Guid>("NinjaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Specialization")
                        .HasColumnType("int");

                    b.HasKey("NinjaId");

                    b.ToTable("Ninjas");
                });

            modelBuilder.Entity("NinjAPI.Models.Training", b =>
                {
                    b.Property<Guid>("TrainingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid?>("NinjaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Title")
                        .HasColumnType("int");

                    b.Property<string>("Trainer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrainingId");

                    b.HasIndex("NinjaId");

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("NinjAPI.Models.Training", b =>
                {
                    b.HasOne("NinjAPI.Models.Ninja", "Ninja")
                        .WithMany("Trainings")
                        .HasForeignKey("NinjaId");

                    b.Navigation("Ninja");
                });

            modelBuilder.Entity("NinjAPI.Models.Ninja", b =>
                {
                    b.Navigation("Trainings");
                });
#pragma warning restore 612, 618
        }
    }
}
